#pragma once

#define SIZE_SCREEN_X 0
#define SIZE_SCREEN_Y 0
#define SIZE_PLAYER_X 0
#define SIZE_PLAYER_Y 0
#define SIZE_STAGE_CHIP_X 0
#define SIZE_STAGE_CHIP_Y 0
#define SIZE_STAGE_ARRAY_X 0
#define SIZE_STAGE_ARRAY_Y 0

#define SPEED_PLAYER_JUMP 0
#define SPEED_PLAYER_X_MAX 0
#define SPEED_PLAYER_FALL_MAX 0
#define SPEED_PLAYER_X_ACCELERATION 0
#define SPEED_PLAYER_Y_ACCELERATION 0
#define SPEED_BRAKE 0

#define POS_PLAYER_INIT_X 0
#define POS_PLAYER_INIT_Y 0